apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: polis-file-server
  name: polis-file-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: polis-file-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: polis-file-server
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: polis-configmap
        image: registry.gitlab.com/particiapp/polis/file-server
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - nc -w 1 127.0.0.1 8080
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: polis-file-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
