apiVersion: v1
kind: Service
metadata:
  labels:
    name: particiapi
  name: particiapi
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 5000
  selector:
    name: particiapi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
