apiVersion: v1
kind: Service
metadata:
  labels:
    name: polis-frontend
  name: polis-frontend
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: polis-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
