apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: particiapi
  name: particiapi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: particiapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: particiapi
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: polis-configmap      
        image: nigledev/particiapi:latest
        imagePullPolicy: Always
        name: particiapi
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

