apiVersion: v1
kind: Secret
metadata:
  name: polis-secrets
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  particiapi-secret-key: {{ .Values.particiApi.secretKey | default (randAlphaNum 32) | b64enc | quote }}
  particiapi-idp-secret: {{ .Values.particiApi.idpClientSecret | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | default (randAlphaNum 32) | b64enc | quote }}
