apiVersion: v1
kind: Service
metadata:
  labels:
    name: polis-server
  name: polis-server
spec:
  ports:
  - name: polis
    port: 5000
    protocol: TCP
    targetPort: 8080
  selector:
    name: polis-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

