apiVersion: v1
kind: Service
metadata:
  labels:
    name: polis-file-server
  name: polis-file-server
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: polis-file-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

